// cube.fe
// Evolver data for cube of prescribed volume.

vertices
1  -1.0 0.0 -1.0 
2  1.0 0.0 -1.0
3  1.0 2.0 -1.0
4  -1.0 2.0 -1.0
5  -1.0 0.0 1.0
6  1.0 0.0 1.0
7  1.0 2.0 1.0
8  -1.0 2.0 1.0
// Second cube
9  -1.0 -2.0 -1.0 
10 1.0 -2.0 -1.0
11 -1.0 -2.0 1.0
12 1.0 -2.0 1.0
// Third cube
13  -1.0 -4.0 -1.0 
14  1.0 -4.0 -1.0
15  -1.0 -4.0 1.0
16  1.0 -4.0 1.0

edges  /* given by endpoints and attribute */
1   1 2   
2   2 3   
3   3 4  
4   4 1 
5   5 6
6   6 7  
7   7 8 
8   8 5
9   1 5   
10  2 6  
11  3 7 
12  4 8
// Second cube
13  9 10
14  11 12
15  9 11
16 10 12
17 10 2
18 1 9
19 12 6
20 5 11
// Third cube
21  13 14
22  15 16
23  13 15
24 14 16
25 14 10
26 9 13
27 16 12
28 11 15

faces  /* given by oriented edge loop */
1   1 10 -5  -9
2   2 11 -6 -10
3   3 12 -7 -11
4   4  9 -8 -12
5   5  6  7   8
6  -4 -3 -2  -1
// Second cube
7  13 16 -14 -15
8  17 10 -19 -16
9  18 15 -20 -9
10 14 19 -5 20
11 1 -17 -13 -18
// Third cube
12 21 24 -22 -23
13 25 16 -27 -24
14 26 23 -28 -15
15 22 27 -14 28
16 13 -25 -21 -26

bodies
1   1 2 3 4 5 6 volume 8 
2   -1 7 8 9 10 11 volume 6
3   -7 12 13 14 15 16 volume 10

read

// Typical evolution to sphere
gogo := { g 5; r; g 5; hessian; r; g 5; hessian; }

// Evolution to very high accuracy, using higher-order Lagrange elements.
// To be run on original datafile.
gogo2 := { g 5; r; g 5; hessian; r; g 5; hessian;
           lagrange 2; g 5; hessian; 
           lagrange 4; g 5; hessian; 
           lagrange 6; g 5; hessian; 
           ideal_rad := (3*body[1].volume/4/pi)^(1/3);
           printf "Area error: %g\n",total_area - 4*pi*ideal_rad^2;
           printf "Vertex radius spread: %g\n",
             max(vertex,sqrt((x-.5)^2+(y-.5)^2+(z-.5)^2))
               - min(vertex,sqrt((x-.5)^2+(y-.5)^2+(z-.5)^2));
}
